### ISSUE TITLE
mpvue 使用记录

### ISSUE THREAD

**Issue by 4096void** [4096void/blogs#5]
> 绝对定位的图片，如果有绑定点击事件，记得同时设置宽高
```css
.width-fixed-absolute-imgs {
  position: absolute;
  top: 90rpx;
  left: 20rpx;

  /* 如果图片还绑定了点击事件，上面的规则是不够的，看情况添加以下规则 */
  width: 20rpx;
  height: 20rpx;
  z-index: 2;
}
```

> 动画，小程序不能解析 `-moz-` `-o-` `-webkit-` 这种带前缀的规则
```css
<style lang="stylus">
// original styles
</style>
<style>
// 手动在需要的地方部分禁用 autoprefixer
/* autoprefixer: off */
@keyframe anime1 {
  0% { display: none; } 
  100% { diaplay: block; }
}
</style>
```
> ~~原生组件，这应该是[小程序文档自己没写好](https://developers.weixin.qq.com/miniprogram/dev/component/swiper.html)的问题：swiper 的属性写错了 `indicator-dots(incorrect)` `indicatordots(correct)`~~（现已和文档规范一致）
```vue
<template lang="jade">
  .container
    //- older workds
    swiper(:indicatordots="false")
    //- newer works
    swiper(:indicator-dots="false")
</template>
```

> 第三方库，window 是 undefined 的，old school 的挂载在 window 上的第三方库不改就用不了了
```javascript
// old school 3rd part libs
(function() {
  // main logics
})(window);

// add this
window = window || {};

export default {
  window,
};
```

> mpvue 路由，某一 `page` 目录下的 `index.vue` 才可以访问，`app.vue` 访问不了
```javascript
// pages/page1/index.vue
this.$root.$mp.query.parameter1; // 👌

// src/app.vue
this.$root.$mp.query.parameter1; // no 👌
```

> `page` 的 `data` 被缓存了
1. 页面加载 -> 当前页面的 model 也初始化完成
2. 执行某项操作，跳到别的页面去了，修改先前页面的 model （可能）
3. 返回上一页，model 应该会被重新初始化一遍，但并没有
```javascript
onLoad() {
  loadData()
    .then(dataSrc => {
      this.data = {}; // 不 reset 的话，可能存留缓存数据
      this.data = dataSrc;
    });
},
```
